version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:Z
      - backup_postgres:/data/backup_postgres:z,ro
    env_file:
      - postgres.env

  redis:
    image: redis:alpine
    restart: always

  nextcloud-app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - OVERWRITEPROTOCOL=https
    env_file:
      - postgres.env
    depends_on:
      - postgres
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:z,ro
    env_file:
      - web.env
    depends_on:
      - nextcloud-app
    networks:
      - proxy-tier
      - default

  nextcloud-cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - postgres
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:z,ro
      - vhost.d:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/tmp/docker.sock:z,ro
    networks:
      - proxy-tier

  letsencrypt:
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs:z
      - acme:/etc/acme.sh:z
      - vhost.d:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/var/run/docker.sock:z,ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  wireguard:
    image: weejewel/wg-easy
    restart: always
    env_file:
      - wireguard.env
    volumes:
      - wireguard_config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  dyndns:
    build: ./dyndns
    restart: always
    env_file:
      - dyndns.env

  backup:
    build: ./backup
    hostname: home-server-backup
    restart: always
    env_file:
      - backup.env
      - postgres.env
    volumes:
      - backup_postgres:/data/backup_postgres:z
      - backup_logs:/data/backup_logs
      - wireguard_config:/data/wireguard_config:z,ro
      - nextcloud:/data/nextcloud:z,ro
      - certs:/data/certs:z,ro
      - vhost.d:/data/vhost.d:z,ro
      - html:/data/html:z,ro
      - acme:/data/acme.sh:z,ro
      - deluge_config:/data/deluge_config:z,ro

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    restart: always
    volumes:
      - deluge_config:/config:z
      - deluge_dowloads:/downloads
    ports:
      - 58846:58846 # daemon
      - 8112:8112 # web ui
      - 43289:43289 # data
      - 43289:43289/udp # data

volumes:
  postgres:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:
  wireguard_config:
  backup_postgres:
  backup_logs:
  deluge_config:
  deluge_dowloads:



networks:
  proxy-tier:
